import { ROUTES } from '../../utils/routes'
import {
  baseStageTypes,
  currentStageDimensions,
  editorLibraryCategories,
  editorViewModes,
  exportReadiness,
  objectLibraryGroups,
  projectLoadLabel,
  stageWarnings,
  state,
  viewportModeLabel
} from '../app/stageState'

export function renderLeftPanel(title, body) {
  return `<aside class="stage-editor-library"><header><h3>${title}</h3><button type="button" aria-label="Close panel" aria-disabled="true">×</button></header>${body}</aside>`
}

export function renderLeftPanelBySection(title, stamp) {
  const section = state.activeStageSection || 'home'
  const dims = currentStageDimensions()
  const unit = dims.unit || state.editorProject?.units || 'ft'
  const load = projectLoadLabel()
  const loadWarning = load === 'fallback' || load === 'error'
    ? '<p class="stage-subtle-warning">Project data failed to load. Editing fallback stage.</p>'
    : ''
  if (section === 'object') return renderLeftPanel('OBJECT LIBRARY', `<div class="stage-editor-library-tools"><input aria-label="Search object library" placeholder="Search objects, fixtures, inputs" /><button type="button" class="stage-library-filter" aria-disabled="true" title="Filters">⌕</button></div><label class="stage-editor-check"><input type="checkbox" checked /> Add as stage-aware objects</label>${objectLibraryGroups.map((group) => `<h4>${group.label.toUpperCase()}</h4><div class="stage-object-grid is-assets">${group.assets.map((asset) => `<button class="stage-object-tile ${state.activeLibraryCategory === asset.category ? 'is-active' : ''}" data-add-stage-asset="${asset.id}" draggable="true" type="button" title="Add ${asset.label}"><span class="stage-object-fallback-icon">${asset.icon}</span><small>${asset.label}</small></button>`).join('')}</div>`).join('')}<h4>PRODUCTION CATEGORIES</h4><div class="stage-object-grid">${editorLibraryCategories.map((c) => `<button class="stage-object-tile ${state.activeLibraryCategory === c.key ? 'is-active' : ''}" data-library-category="${c.key}" data-select-object="${c.select}" type="button"><span class="stage-object-icon-frame" data-stage-icon-path="${c.iconPath}"><img alt="" loading="lazy" hidden /><span class="stage-object-fallback-icon">${c.icon}</span></span><small>${c.label}</small></button>`).join('')}</div><h4>BASE STAGE TYPES</h4><div class="stage-base-stage-grid">${baseStageTypes.map((stage) => `<button class="stage-base-stage-card" data-select-object="stage-deck" type="button"><span class="stage-base-stage-thumb" data-stage-icon-path="${stage.icon}"><img alt="" loading="lazy" hidden /><span>${stage.label.slice(0, 2).toUpperCase()}</span></span><span>${stage.label}</span></button>`).join('')}</div>`)

  const base = `<section class="stage-config-panel"><h3>${section.toUpperCase()}</h3><div class="stage-detail-list"><div><span>Project</span><strong>${title}</strong></div><div><span>Date/Version</span><strong>${stamp} | v${state.editorProject?.version || 1}</strong></div><div><span>Stage Type</span><strong>${state.editorProject?.stageType || 'Blank Stage'}</strong></div><div><span>Status</span><strong>Foundation Preview</strong></div><div><span>Load State</span><strong>${load}</strong></div></div>${loadWarning}</section>`
  const readiness = exportReadiness()
  const warnings = stageWarnings()
  const map = {
    home: `${base}<section class="stage-config-panel"><h3>Current View</h3><div class="stage-detail-list"><div><span>View Mode</span><strong>${viewportModeLabel()}</strong></div><div><span>Grid</span><strong>${state.gridEnabled ? 'On' : 'Off'}</strong></div><div><span>Snap</span><strong>${state.snapEnabled ? 'On' : 'Off'}</strong></div><div><span>Save</span><strong>${state.editorSaveStatus || 'ready'}</strong></div></div></section><section class="stage-config-panel"><h3>Quick Actions</h3><div class="stage-action-grid"><button type="button" data-new-stage-plan>New Stage</button><a href="${ROUTES.stage}">Open Project</a><button type="button" aria-disabled="true">Duplicate</button><button type="button" data-open-export>Export</button><button type="button" aria-disabled="true">Share</button></div></section>`,
    scene: `${base}<section class="stage-config-panel"><h3>Scene</h3><div class="stage-field-grid"><label>Stage width<input type="number" value="${dims.width || 32}" step="1" disabled></label><label>Stage depth<input type="number" value="${dims.depth || 24}" step="1" disabled></label><label>Deck height<input type="number" value="${dims.deckHeight || 4}" step="0.5" disabled></label><label>Units<input type="text" value="${unit}" disabled></label><label class="stage-editor-check"><input data-toggle-grid-control type="checkbox" ${state.gridEnabled ? 'checked' : ''}> Grid visibility</label><label>Grid size<input type="number" value="1" disabled></label><label>Snap interval<input data-snap-interval type="number" min="0.25" step="0.25" value="${state.snapInterval}"></label><label class="stage-editor-check"><input data-toggle-labels type="checkbox" ${state.showStageLabels ? 'checked' : ''}> Show labels</label></div><label class="stage-full-field">Scene notes<textarea placeholder="Scene notes">Staging baseline configured.</textarea></label></section>`,
    lighting: `${base}<section class="stage-config-panel"><h3>Lighting</h3><label class="stage-editor-check"><input data-toggle-beam-control type="checkbox" ${state.beamPreviewEnabled ? 'checked' : ''}> Beam Preview</label><div class="stage-render-mode-row"><button type="button" data-render-mode="simple" class="${state.renderMode === 'simple' ? 'is-active' : ''}">Simple</button><button type="button" data-render-mode="technical" class="${state.renderMode === 'technical' ? 'is-active' : ''}">Technical</button><button type="button" data-render-mode="beam" class="${state.renderMode === 'beam' ? 'is-active' : ''}">Beam</button><button type="button" data-render-mode="export-clean" class="${state.renderMode === 'export-clean' ? 'is-active' : ''}">Export</button></div><div class="stage-field-grid"><label>Fixture type<select><option>Moving Head</option><option>LED Par</option><option>Profile</option></select></label><label>DMX universe<input type="number" value="1"></label><label>DMX address<input type="number" value="1"></label><label>Beam angle<input type="text" value="15-45 deg"></label><label>Color<input type="color" value="#31c9ff"></label></div><button type="button" class="stage-inline-button" data-add-stage-asset="asset-moving-head">Add Fixture</button><label class="stage-full-field">Lighting notes<textarea placeholder="Lighting notes">Key, rim, and front wash ready.</textarea></label></section>`,
    rigging: `${base}<section class="stage-config-panel"><h3>Rigging</h3><div class="stage-action-grid"><button type="button" data-add-stage-asset="asset-truss">Add Truss</button><button type="button" aria-disabled="true">Add Rigging Point</button></div><label class="stage-full-field">Rigging notes<textarea placeholder="Rigging notes">Ground support placeholders only.</textarea></label><p class="stage-safety-note">Qualified personnel required for rigging/hangs. Load calculation required by qualified rigger.</p></section>`,
    audio: `${base}<section class="stage-config-panel"><h3>Audio</h3><div class="stage-detail-list"><div><span>Input List</span><strong>${state.editorProject?.audioInputs?.length || 0} channels</strong></div><div><span>Monitor/Speaker</span><strong>Placement placeholders</strong></div></div><div class="stage-action-grid"><button type="button" data-add-stage-asset="asset-vocal-mic">Add Vocal Mic</button><button type="button" data-add-stage-asset="asset-wedge-monitor">Add Wedge</button><button type="button" data-add-stage-asset="asset-bass-di">Add Bass DI</button><button type="button" data-add-stage-asset="asset-playback-rack">Playback Rig</button></div><label class="stage-full-field">Mic/DI notes<textarea placeholder="Mic/DI notes"></textarea></label><label class="stage-full-field">Patch notes<textarea placeholder="Patch notes"></textarea></label></section>`,
    video: `${base}<section class="stage-config-panel"><h3>Video</h3><div class="stage-action-grid"><button type="button" data-add-stage-asset="asset-led-wall">Add LED Wall</button><button type="button" data-add-stage-asset="asset-camera">Add Camera</button><button type="button" aria-disabled="true">Add Projector</button><button type="button" aria-disabled="true">Screen</button></div><label class="stage-full-field">Video notes<textarea placeholder="Video notes">FOH wide camera placeholder active.</textarea></label></section>`,
    venue: `${base}<section class="stage-config-panel"><h3>Venue</h3><div class="stage-field-grid"><label>Venue name<input value="${state.editorProject?.venue?.name || 'Main Hall'}"></label><label>FOH position<input value="${state.editorProject?.venue?.fohPosition || 'Center'}"></label></div><label class="stage-full-field">Loading notes<textarea placeholder="Loading notes">${state.editorProject?.venue?.loadingNotes || ''}</textarea></label><label class="stage-full-field">Power notes<textarea placeholder="Power notes">${state.editorProject?.venue?.powerNotes || ''}</textarea></label><label class="stage-full-field">Room notes<textarea placeholder="Room notes">${state.editorProject?.venue?.roomType || ''}</textarea></label></section>`,
    export: `${base}<section class="stage-config-panel"><h3>Export Packet</h3><div class="stage-action-grid"><button type="button" data-open-export>Preview Packet</button><button type="button" aria-disabled="true">Export PDF</button><button type="button" aria-disabled="true">Export SVG</button><button type="button" aria-disabled="true">Export JSON</button></div><ul class="stage-help-list">${readiness.map((item) => `<li>${item.ok ? '✓' : '⚠'} ${item.label}</li>`).join('')}</ul>${warnings.length ? `<p class="stage-subtle-warning">${warnings.length} export warning${warnings.length === 1 ? '' : 's'} need review.</p>` : '<p class="stage-safety-note">Export checklist is clean.</p>'}</section>`,
    settings: `${base}<section class="stage-config-panel"><h3>Settings</h3><div class="stage-field-grid"><label>Units<select><option>${unit}</option></select></label><label>Default snap<input data-snap-interval type="number" min="0.25" step="0.25" value="${state.snapInterval}"></label><label>Default view<select data-default-view-mode>${editorViewModes.map(([k, l]) => `<option value="${k}" ${state.viewportMode === k ? 'selected' : ''}>${l}</option>`).join('')}</select></label><label>Theme density<input value="Compact" disabled></label></div><label class="stage-editor-check"><input data-toggle-viewport-diagnostics type="checkbox" ${state.showViewportDiagnostics ? 'checked' : ''}> Show viewport diagnostics</label><label class="stage-editor-check"><input type="checkbox" checked disabled> Autosave editor state</label></section>`,
    help: `${base}<section class="stage-config-panel"><h3>Help</h3><ul class="stage-help-list"><li>Orbit in 3D with drag; pan with right-drag; zoom with the wheel.</li><li>Top, Front, Side, and Iso use framed planning views with pan and zoom.</li><li>Use Object Library tiles to select stage objects; drag/drop wiring remains staged.</li><li>Grid, snap, labels, and measure controls expose planning state in the viewport.</li><li>Resize handles adjust the library, inspector, bottom panel, and bottom split.</li></ul></section>`
  }
  return renderLeftPanel(section.toUpperCase(), map[section] || base)
}
