// melogic-toolbox-foundation-v1
import {ROUTES} from '../../utils/routes.js'
import {TOOLBOX_CATEGORIES,TOOLBOX_TOOLS,getToolboxTool,searchToolboxTools} from './toolRegistry.js'
import {hasToolHandler} from './toolRuntime.js'
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const category=k=>TOOLBOX_CATEGORIES.find(([id])=>id===k)?.[1]||k;const route=s=>`${ROUTES.toolbox}/${encodeURIComponent(s)}`
const icon=t=>`<span class="studio-toolbox-card-icon" aria-hidden="true">${esc(t.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase())}</span>`
const card=t=>`<a class="studio-toolbox-card" href="${route(t.slug)}" data-studio-shell-nav data-tool-card="${esc(t.slug)}">${icon(t)}<span class="studio-toolbox-card-copy"><strong>${esc(t.name)}</strong><small>${esc(category(t.category))}</small><span>${esc(t.description)}</span></span><span class="studio-toolbox-card-arrow">›</span></a>`
function catalog(){return `<section class="studio-main studio-toolbox" data-toolbox-page="catalog"><header class="studio-toolbox-hero"><span class="studio-toolbox-eyebrow">CREATOR UTILITIES</span><h1>Toolbox</h1><p>Fast tools for audio, images, video, 3D, stage production, documents, publishing, and creator files.</p><div class="studio-toolbox-search-row"><input type="search" placeholder="Search creator tools..." data-toolbox-search><span data-toolbox-count>${TOOLBOX_TOOLS.length} tools</span></div></header><nav class="studio-toolbox-categories"><button class="is-active" data-toolbox-category="all">All Tools</button>${TOOLBOX_CATEGORIES.map(([k,n])=>`<button data-toolbox-category="${k}">${esc(n)}</button>`).join('')}</nav><div class="studio-toolbox-grid" data-toolbox-grid>${TOOLBOX_TOOLS.map(card).join('')}</div><div data-toolbox-empty hidden>No tools match this search.</div></section>`}
function device(t){const live=hasToolHandler(t.slug);return `<section class="studio-main studio-toolbox" data-toolbox-page="device"><a href="${ROUTES.toolbox}" data-studio-shell-nav>← All tools</a><header class="studio-toolbox-device-header">${icon(t)}<div><span class="studio-toolbox-eyebrow">${esc(category(t.category))}</span><h1>${esc(t.name)}</h1><p>${esc(t.description)}</p></div></header><section class="studio-tool-device-shell"><div class="studio-tool-device-dropzone"><strong>Drop files here</strong><span>Tool input surface initialized.</span><button type="button" data-tool-pick>Choose files</button><input type="file" hidden data-tool-file-input></div><aside class="studio-tool-device-panel"><h2>Tool controls</h2><p class="studio-tool-device-status">${live?'Runtime available.':'Tool UI initialized. Processing implementation is not installed yet.'}</p><div data-tool-controls>Tool-specific controls mount here.</div><button data-tool-run ${live?'':'disabled'}>Run ${esc(t.name)}</button></aside></section></section>`}
export function renderToolboxPage(path=window.location.pathname){const p=`${ROUTES.toolbox}/`;if(!path.startsWith(p))return catalog();const t=getToolboxTool(decodeURIComponent(path.slice(p.length).split('/')[0]||''));return t?device(t):`<section class="studio-main studio-toolbox"><h1>Tool not found</h1><a href="${ROUTES.toolbox}" data-studio-shell-nav>Return to Toolbox</a></section>`}
export function bindToolboxPage(root){const page=root?.querySelector?.('[data-toolbox-page]');if(!page)return;let cat='all';const q=page.querySelector('[data-toolbox-search]'),grid=page.querySelector('[data-toolbox-grid]'),count=page.querySelector('[data-toolbox-count]'),empty=page.querySelector('[data-toolbox-empty]');const refresh=()=>{if(!grid)return;const results=searchToolboxTools(q?.value||'',cat),visible=new Set(results.map(t=>t.slug));grid.querySelectorAll('[data-tool-card]').forEach(n=>n.hidden=!visible.has(n.dataset.toolCard));if(count)count.textContent=`${results.length} tool${results.length===1?'':'s'}`;if(empty)empty.hidden=!!results.length};q?.addEventListener('input',refresh);page.querySelectorAll('[data-toolbox-category]').forEach(b=>b.addEventListener('click',()=>{cat=b.dataset.toolboxCategory||'all';page.querySelectorAll('[data-toolbox-category]').forEach(x=>x.classList.toggle('is-active',x===b));refresh()}));const pick=page.querySelector('[data-tool-pick]'),input=page.querySelector('[data-tool-file-input]');pick?.addEventListener('click',()=>input?.click())}
