set(ORIGAMI_BUILD_CHANNEL "development" CACHE STRING "Release channel")
string(TOLOWER "${ORIGAMI_BUILD_CHANNEL}" ORIGAMI_RELEASE_CHANNEL)
set(ORIGAMI_BUILD_NUMBER "0" CACHE STRING "Explicit release automation build number; development uses 0")
if(NOT ORIGAMI_RELEASE_CHANNEL MATCHES "^(development|internal|beta|stable)$")
  message(FATAL_ERROR "Invalid Origami release channel")
endif()
if(NOT ORIGAMI_BUILD_NUMBER MATCHES "^(0|[1-9][0-9]*)$" OR ORIGAMI_BUILD_NUMBER GREATER 2147483647)
  message(FATAL_ERROR "Invalid Origami build number")
endif()
if(ORIGAMI_RELEASE_CHANNEL STREQUAL "development")
  if(NOT ORIGAMI_BUILD_NUMBER STREQUAL "0")
    message(FATAL_ERROR "Development builds must use build number 0")
  endif()
  set(ORIGAMI_BUILD_CHANNEL "DEVELOPMENT")
elseif(ORIGAMI_BUILD_NUMBER LESS 1)
  message(FATAL_ERROR "Publishable channels require an explicit positive build number")
endif()
# CMake/JUCE bundle versions retain the numeric core. Native release identity
# may add a strictly validated SemVer prerelease suffix (e.g. beta.1).
set(ORIGAMI_VERSION_PRERELEASE "" CACHE STRING "Optional SemVer prerelease identifiers")
if(NOT ORIGAMI_VERSION_PRERELEASE STREQUAL "")
  string(LENGTH "${ORIGAMI_VERSION_PRERELEASE}" prerelease_length)
  if(prerelease_length GREATER 64 OR NOT ORIGAMI_VERSION_PRERELEASE MATCHES "^(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*)(\\.(0|[1-9][0-9]*|[0-9]*[A-Za-z-][0-9A-Za-z-]*))*$")
    message(FATAL_ERROR "Invalid Origami SemVer prerelease suffix")
  endif()
endif()
set(ORIGAMI_RELEASE_VERSION "${PROJECT_VERSION}")
if(NOT ORIGAMI_VERSION_PRERELEASE STREQUAL "")
  string(APPEND ORIGAMI_RELEASE_VERSION "-${ORIGAMI_VERSION_PRERELEASE}")
endif()
