# Public build identity only. Never embed checkout paths or git remote data.
set(ORIGAMI_SOURCE_REVISION "source-archive")
if(EXISTS "${GIT_EXECUTABLE}")
  execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --short=10 HEAD WORKING_DIRECTORY "${SOURCE_ROOT}" OUTPUT_VARIABLE revision OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE result)
  if(result EQUAL 0 AND revision MATCHES "^[0-9a-f]+$")
    set(ORIGAMI_SOURCE_REVISION "${revision}")
    execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=normal -- origami shared/melogic config/firebase-client.json WORKING_DIRECTORY "${SOURCE_ROOT}" OUTPUT_VARIABLE changes ERROR_QUIET)
    if(NOT changes STREQUAL "")
      string(APPEND ORIGAMI_SOURCE_REVISION "-modified")
    endif()
  endif()
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
configure_file("${TEMPLATE}" "${OUTPUT_DIR}/OrigamiBuildIdentity.h" @ONLY)
