import { currentStageDimensions, editorTitleStamp, exportReadiness, stageWarnings, state } from '../app/stageState'

export function renderExportPreview() {
  const { title, stamp } = editorTitleStamp()
  const dims = currentStageDimensions()
  const readiness = exportReadiness()
  const warnings = stageWarnings()
  const inputs = state.editorProject?.audioInputs || []
  const fixtures = state.editorProject?.fixtures || []
  return `<div class="stage-export-modal"><div class="stage-export-sheet"><header class="stage-export-titlebar"><div><h3>Stage Plan Packet</h3><p>${title} • ${stamp} • v${state.editorProject?.version || 1}</p></div><button type="button" data-close-export>Close</button></header><div class="stage-export-packet-grid"><section><h4>Cover / Title Block</h4><p>${dims.width || 32} x ${dims.depth || 24} ${dims.unit || 'ft'} stage • ${state.editorProject?.stageType || 'Blank Stage'}</p><p>Prepared for crew review. Export-ready sheets are generated from StagePlan data, not viewport screenshots.</p></section><section><h4>Readiness</h4><ul>${readiness.map((item) => `<li>${item.ok ? '✓' : '⚠'} ${item.label}</li>`).join('')}</ul></section></div><div class="stage-export-drawing"><div class="stage-export-stage-rect"><span>Stage Plot SVG Preview</span></div></div><div class="stage-export-packet-grid"><section><h4>Input List Sheet</h4><p>${inputs.length} channels • Channel / Source / Mic-DI / Stand / Patch / Notes</p></section><section><h4>Lighting Plot Sheet</h4><p>${fixtures.length} fixtures • Universe / Address / Mode / Position / Target</p></section><section><h4>Rigging Notes Sheet</h4><p>Qualified-personnel notes and attachment comments. No structural calculations generated.</p></section><section><h4>Warnings</h4><p>${warnings.length ? `${warnings.length} item${warnings.length === 1 ? '' : 's'} need review before final export.` : 'No blocking warnings detected.'}</p></section></div><div class="stage-export-actions"><button disabled title="PDF export coming soon; vector packet foundation is in place.">Export PDF</button><button disabled>Export PNG</button><button disabled>Export SVG</button><button disabled>Export JSON</button><button disabled>Copy Share Link</button><button data-close-export>Close</button></div></div></div>`
}
